spring.application.name=enterprise-task-service

spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_tasks
spring.datasource.username=xxxxxxxxx
spring.datasource.password=xxxxxxxxx

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration